### PR TITLE
Add missing dependancies for MacOsx to the README

### PR DESCRIPTION
**Pull request by bgok**

### CODE REVIEW

**Comment by kallewoof** [comment]
I don't have either of those installed on my Mac, and I can compile fine.

What is the error you are seeing when you don't have these? How are you installing?

**Comment by bgok** [comment]
Sorry for the lack of detail.

- autogen.sh refused to run with the error message `failed to run aclocal`. Resolution: `brew install autogen`.
- config failed with `can't run pkg-config`. Resolution: `brew install pkg-config` and rerun autogen.sh and config.
- Make warning when referencing a header file from berkeley-db in the brew cellar. Resolution: `brew install berkeley-db@4`, then `make clean`.

**Comment by kallewoof** [comment]
Even on new macs, doing `brew install libtool autoconf` has been sufficient for me.

What version of macOS are you running?

**Comment by bgok** [comment]
My computer: Macbook pro (15 inch, 2019) running Catalina (10.15.2). It is a fairly clean machine. I think this is the first build of a C project that I've run on this computer.

Is it possible that these dependencies were installed on your computer by a prior build of another project? Maybe Bitcoin or libbitcoin?

**Comment by kallewoof** [comment]
Thing is, I don't even have these brew packages installed *now*, and I regularly build and rebuild btcdeb. I suspect these are all included in the `libtool` package, though, which is already listed.

Would you mind trying to do

```
$ brew uninstall autogen pkg-config berkeley-db@4
$ brew install libtool autoconf
```

and then from btcdeb folder, do

```
$ ./autogen.sh
$ ./configure.sh
$ make clean
$ make
```

and print the error you see (if any) here?

**Comment by kallewoof** [comment]
I pushed a change to remove berkeley-db@4 from the build system. What remains to check now is whether you *actually* need autogen (and why), or if `brew install libtool` is enough.

**Comment by bgok** [comment]
I pulled from github into a new directory, so I have the changes that you checked in this morning.

`% brew install libtool autoconf`
```
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
Warning: autoconf 2.69 is already installed and up-to-date
To reinstall 2.69, run `brew reinstall autoconf`
```
`% brew list`
```
autoconf	aws-sam-cli	gdbm		openssl@1.1	readline	xz
automake	berkeley-db	libtool		python		sqlite
```

`% ./autogen.sh` ran without error. **Error not reproduced**

`% ./configure` gives the following error:
```
configure: error: PKG_PROG_PKG_CONFIG macro not found. Please install pkg-config and re-run autogen.sh.
```
**Error Reproduced**
```
% brew install pkg-config
% ./autogen.sh
% ./configure
```
Complete without errors.

`% make clean && make` completed without warnings. **Error not reproduced**

**Comment by bgok** [comment]
Kalle, thanks for drilling down and figuring this out!

**Comment by kallewoof** [comment]
Thanks! :)

**Pull request merged**
